import { readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { createDocxParser } from '../lib/parser/docx'
import type { Block, ParsedDocument } from '../lib/types/document'
import type { ParseOptions } from '../lib/parser/types'

/**
 * Shared test helpers.
 *
 * The fixtures are generated by `fixtures/build-fixtures.mjs` rather than
 * committed as opaque binaries, so what each one contains is readable in
 * version control. Run that script if `fixtures/docx/` is missing.
 */

const FIXTURE_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'fixtures', 'docx')

export async function readFixture(name: string): Promise<ArrayBuffer> {
  const buffer = await readFile(join(FIXTURE_DIR, name))
  return buffer.buffer.slice(
    buffer.byteOffset,
    buffer.byteOffset + buffer.byteLength,
  ) as ArrayBuffer
}

export const defaultParseOptions: ParseOptions = {
  chapterHeadingLevel: 1,
}

/** Parse a fixture, failing the test with a readable message if it errors. */
export async function parseFixture(
  name: string,
  options: Partial<ParseOptions> = {},
): Promise<ParsedDocument> {
  const parser = createDocxParser()
  const bytes = await readFixture(name)

  const result = await parser.parse(
    {
      fileName: name,
      mediaType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      bytes,
    },
    { ...defaultParseOptions, ...options },
  )

  if (!result.ok) {
    throw new Error(
      `Expected ${name} to parse, but got: ${result.error.code} — ${result.error.message}`,
    )
  }

  return result.value
}

/** Parse a fixture expected to fail, returning the error code. */
export async function parseFixtureExpectingError(name: string): Promise<string> {
  const parser = createDocxParser()
  const bytes = await readFixture(name)

  const result = await parser.parse(
    {
      fileName: name,
      mediaType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      bytes,
    },
    defaultParseOptions,
  )

  if (result.ok) throw new Error(`Expected ${name} to fail, but it parsed successfully.`)

  return result.error.code
}

/** All text in a document, for content assertions. */
export function allText(document: ParsedDocument): string {
  const parts: string[] = []

  const walk = (blocks: readonly Block[]): void => {
    for (const block of blocks) {
      switch (block.type) {
        case 'heading':
        case 'paragraph':
          parts.push(block.content.map((run) => run.text).join(''))
          break
        case 'list':
          for (const item of block.items) {
            parts.push(item.content.map((run) => run.text).join(''))
            if (item.children) walk(item.children)
          }
          break
        case 'quote':
        case 'note':
          walk(block.content)
          break
        case 'table':
          for (const row of [...(block.header ?? []), ...block.rows]) {
            for (const cell of row.cells) parts.push(cell.content.map((run) => run.text).join(''))
          }
          break
        case 'code':
          parts.push(block.code)
          break
        default:
          break
      }
    }
  }

  for (const chapter of document.chapters) walk(chapter.blocks)

  return parts.join('\n')
}

/** Every block in the document, flattened across chapters. */
export function allBlocks(document: ParsedDocument): readonly Block[] {
  return document.chapters.flatMap((chapter) => chapter.blocks)
}
