import { CATEGORY_LABEL, IMPACT_LABEL, type QualityReport, type ValidationFinding } from './types'

/**
 * Report export.
 *
 * WHY THREE FORMATS
 * -----------------
 * They are read by three different people. JSON is for a script — a publisher
 * with fifty titles wants to diff two runs, not read fifty pages. HTML is for a
 * human who has to send the results to somebody: an editor, a co-author, a
 * client. Plain text is for a commit message, an email, or an issue.
 *
 * WHY THE HTML IS SELF-CONTAINED
 * ------------------------------
 * One file, no assets, no network. It has to survive being emailed, opened from
 * a download folder six months later, and printed to PDF — which is the actual
 * request behind "PDF-ready", and which every browser does natively from a page
 * with a print stylesheet. Generating a real PDF would mean carrying a
 * rendering engine to produce a worse version of what the browser already has.
 *
 * WHY THE DISCLAIMER IS IN THE OUTPUT AND NOT ONLY THE UI
 * -------------------------------------------------------
 * An exported report travels. Once it is a file in somebody else's inbox, the
 * caveat on the screen it came from is gone, and a document titled "Validation
 * report" reads as certification. It is not: it is a native checker, not
 * EPUBCheck, and it says so in every format.
 */

export interface ReportGenerator {
  toJson(report: QualityReport): string
  toHtml(report: QualityReport): string
  toText(report: QualityReport): string
  /** File name for a download, derived from the book title. */
  fileName(report: QualityReport, extension: string): string
}

const DISCLAIMER =
  'Chiify runs its own checks against the generated package. It is not EPUBCheck and is not official certification — retailers run their own validation at submission.'

export function createReportGenerator(): ReportGenerator {
  return {
    toJson(report) {
      return JSON.stringify(
        {
          generator: 'Chiify Toolkit',
          checkedAt: report.checkedAt,
          disclaimer: DISCLAIMER,
          book: report.subject,
          score: report.score,
          summary: report.summary,
          categories: report.categories,
          compatibility: report.compatibility,
          checksRun: report.totalChecks,
          inspectors: report.inspectors,
          findings: report.findings.map((item) => ({
            rule: item.rule,
            category: item.category,
            severity: item.severity,
            impact: item.impact,
            message: item.message,
            location: item.location ?? null,
            remedy: item.remedy ?? null,
          })),
        },
        null,
        2,
      )
    },

    toText(report) {
      const lines: string[] = [
        `${report.subject.title} — validation report`,
        `Checked ${formatDate(report.checkedAt)} · ${report.totalChecks} checks`,
        '',
        report.score.headline,
        `Score ${report.score.overall}/100 (${report.score.grade}) · ${report.summary.errors} errors, ${report.summary.warnings} warnings, ${report.summary.infos} notes`,
        '',
      ]

      for (const category of report.categories) {
        lines.push(`${category.label.padEnd(24)} ${String(category.score).padStart(3)}/100`)
      }

      if (report.findings.length > 0) {
        lines.push('', 'Findings', '--------')

        for (const item of report.findings) {
          lines.push(`[${item.severity.toUpperCase()}] ${item.message}`)
          if (item.location) lines.push(`  where: ${item.location}`)
          if (item.remedy) lines.push(`  fix:   ${item.remedy}`)
          lines.push('')
        }
      }

      lines.push('', DISCLAIMER)

      return lines.join('\n')
    },

    toHtml(report) {
      return [
        '<!doctype html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="utf-8"/>',
        '<meta name="viewport" content="width=device-width, initial-scale=1"/>',
        `<title>${escapeHtml(report.subject.title)} — validation report</title>`,
        `<style>${REPORT_CSS}</style>`,
        '</head>',
        '<body>',
        header(report),
        scoreSection(report),
        compatibilitySection(report),
        findingsSection(report.findings),
        `<footer><p>${escapeHtml(DISCLAIMER)}</p><p>Generated by Chiify Toolkit on ${formatDate(report.checkedAt)}.</p></footer>`,
        '</body>',
        '</html>',
      ].join('\n')
    },

    fileName(report, extension) {
      const stem =
        report.subject.title
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-+|-+$/g, '')
          .slice(0, 40) || 'book'

      return `${stem}-validation.${extension}`
    },
  }
}

function header(report: QualityReport): string {
  const authors = report.subject.authors.join(', ')

  return [
    '<header>',
    '<p class="eyebrow">Validation report</p>',
    `<h1>${escapeHtml(report.subject.title)}</h1>`,
    `<p class="meta">${escapeHtml(authors || 'No author')} · ${report.subject.chapters} chapters · ${report.subject.images} images · ${formatSize(report.subject.byteSize)}</p>`,
    '</header>',
  ].join('\n')
}

function scoreSection(report: QualityReport): string {
  const bars = report.categories
    .map(
      (category) =>
        `<tr><th scope="row">${escapeHtml(category.label)}</th><td><span class="bar"><span class="fill ${band(category.score)}" style="width:${category.score}%"></span></span></td><td class="num">${category.score}</td><td class="num">${category.checks}</td></tr>`,
    )
    .join('\n')

  return [
    '<section>',
    `<div class="score ${band(report.score.overall)}"><strong>${report.score.overall}</strong><span>out of 100 · grade ${report.score.grade}</span></div>`,
    `<p class="headline">${escapeHtml(report.score.headline)}</p>`,
    `<p class="meta">${report.summary.errors} errors · ${report.summary.warnings} warnings · ${report.summary.infos} notes · ${report.totalChecks} checks run</p>`,
    '<table><caption>Scores by area</caption><thead><tr><th scope="col">Area</th><th scope="col">Score</th><th scope="col">/100</th><th scope="col">Checks</th></tr></thead><tbody>',
    bars,
    '</tbody></table>',
    '</section>',
  ].join('\n')
}

function compatibilitySection(report: QualityReport): string {
  if (report.compatibility.targets.length === 0) return ''

  const rows = report.compatibility.targets
    .map((target) => {
      const notes =
        target.notes.length === 0
          ? '<li>No problems found.</li>'
          : target.notes.map((note) => `<li>${escapeHtml(note)}</li>`).join('')

      return `<tr><th scope="row">${escapeHtml(target.name)}<small>${escapeHtml(target.vendor)}</small></th><td><span class="pill ${target.status}">${target.status}</span></td><td><ul>${notes}</ul></td></tr>`
    })
    .join('\n')

  return [
    '<section>',
    `<h2>Devices and stores</h2>`,
    `<p class="meta">${report.compatibility.supported} of ${report.compatibility.total} accept this book as it stands.</p>`,
    '<table><tbody>',
    rows,
    '</tbody></table>',
    '</section>',
  ].join('\n')
}

function findingsSection(findings: readonly ValidationFinding[]): string {
  if (findings.length === 0) {
    return '<section><h2>Findings</h2><p class="pass">Nothing to report — every check passed.</p></section>'
  }

  const items = findings
    .map((item) =>
      [
        `<li class="finding ${item.severity}">`,
        `<p class="what"><span class="pill ${item.severity}">${item.severity}</span> ${escapeHtml(item.message)}</p>`,
        `<p class="meta">${escapeHtml(CATEGORY_LABEL[item.category])} · ${escapeHtml(IMPACT_LABEL[item.impact])}${item.location ? ` · ${escapeHtml(item.location)}` : ''}</p>`,
        item.remedy ? `<p class="remedy">${escapeHtml(item.remedy)}</p>` : '',
        '</li>',
      ].join(''),
    )
    .join('\n')

  return [
    '<section>',
    '<h2>Findings</h2>',
    '<ol class="findings">',
    items,
    '</ol>',
    '</section>',
  ].join('\n')
}

function band(score: number): string {
  if (score >= 90) return 'good'
  if (score >= 70) return 'fair'
  return 'poor'
}

function formatDate(iso: string): string {
  const date = new Date(iso)
  return Number.isNaN(date.getTime()) ? iso : date.toISOString().replace('T', ' ').slice(0, 16)
}

function formatSize(bytes: number): string {
  if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
  if (bytes >= 1024) return `${Math.round(bytes / 1024)} KB`
  return `${bytes} bytes`
}

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Report styling.
 *
 * Light-only and system-font: an exported report is printed and emailed far
 * more often than it is read on the screen it was made on, and neither a dark
 * background nor a webfont survives either journey.
 */
const REPORT_CSS = [
  ':root{color-scheme:light;--ink:#18181b;--muted:#52525b;--line:#e4e4e7;--good:#15803d;--fair:#b45309;--poor:#b91c1c}',
  '*{box-sizing:border-box}',
  'body{margin:0 auto;padding:2.5rem 1.5rem;max-width:52rem;font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:var(--ink);background:#fff}',
  'header{border-bottom:1px solid var(--line);padding-bottom:1.5rem;margin-bottom:2rem}',
  '.eyebrow{margin:0;text-transform:uppercase;letter-spacing:.08em;font-size:.75rem;color:var(--muted)}',
  'h1{margin:.25rem 0 .5rem;font-size:1.75rem;line-height:1.2}',
  'h2{margin:2.5rem 0 .75rem;font-size:1.15rem}',
  '.meta{margin:.25rem 0;color:var(--muted);font-size:.875rem}',
  '.headline{margin:1rem 0;font-size:1.05rem}',
  '.score{display:flex;align-items:baseline;gap:.75rem;margin-top:1.5rem}',
  '.score strong{font-size:3rem;line-height:1}',
  '.score.good strong{color:var(--good)}.score.fair strong{color:var(--fair)}.score.poor strong{color:var(--poor)}',
  '.score span{color:var(--muted);font-size:.9rem}',
  'table{width:100%;border-collapse:collapse;margin-top:1rem;font-size:.9rem}',
  'caption{text-align:left;font-weight:600;padding-bottom:.5rem}',
  'th,td{text-align:left;padding:.5rem .5rem .5rem 0;border-bottom:1px solid var(--line);vertical-align:top}',
  'th small{display:block;font-weight:400;color:var(--muted)}',
  '.num{text-align:right;font-variant-numeric:tabular-nums;width:4rem}',
  '.bar{display:block;height:.5rem;border-radius:999px;background:var(--line);overflow:hidden;min-width:8rem}',
  '.fill{display:block;height:100%;border-radius:999px}',
  '.fill.good{background:var(--good)}.fill.fair{background:var(--fair)}.fill.poor{background:var(--poor)}',
  '.pill{display:inline-block;padding:.1rem .45rem;border-radius:999px;font-size:.7rem;text-transform:uppercase;letter-spacing:.04em;border:1px solid var(--line)}',
  '.pill.error,.pill.rejected{color:var(--poor);border-color:var(--poor)}',
  '.pill.warning,.pill.degraded{color:var(--fair);border-color:var(--fair)}',
  '.pill.info,.pill.supported{color:var(--good);border-color:var(--good)}',
  'ul{margin:0;padding-left:1.1rem}',
  '.findings{list-style:none;padding:0;margin:1rem 0 0}',
  '.finding{border-left:3px solid var(--line);padding:.75rem 0 .75rem 1rem;margin-bottom:.75rem}',
  '.finding.error{border-color:var(--poor)}.finding.warning{border-color:var(--fair)}',
  '.what{margin:0 0 .25rem;font-weight:500}',
  '.remedy{margin:.35rem 0 0;color:var(--muted);font-size:.9rem}',
  '.pass{color:var(--good);font-weight:500}',
  'footer{margin-top:3rem;padding-top:1.5rem;border-top:1px solid var(--line);color:var(--muted);font-size:.8rem}',
  '@media print{body{padding:0;max-width:none}.finding{break-inside:avoid}}',
].join('')
