import { ok, type Result } from '../utils/result'

import { OCF_PATHS } from './constants'
import { safeXmlId } from './naming'
import type { CssGenerator, GeneratedFile, GenerationContext } from './types'

/**
 * The book's stylesheet.
 *
 * THE GOVERNING PRINCIPLE: THE READER IS IN CHARGE
 * ------------------------------------------------
 * A print stylesheet specifies. An EPUB stylesheet *suggests*. Readers change
 * the font, the size, the margins, the background and the line spacing, and a
 * reading system may override anything it likes. So this CSS is deliberately
 * restrained, and every rule below follows from that:
 *
 *   - **No fixed font sizes.** Everything is in `em`, relative to whatever the
 *     reader has chosen. A book that specifies `12pt` body text is unreadable
 *     for someone who needs 24pt and cannot be fixed by them.
 *   - **No colours on body text.** Setting `color: #333` looks refined on white
 *     and is invisible in a reader's night mode, because the reading system
 *     changes the background and not the text. This is the single most common
 *     complaint about self-published EPUBs.
 *   - **No fixed widths.** The reading system owns the viewport.
 *   - **`max-width: 100%` on images**, so an illustration wider than a phone
 *     scales instead of forcing horizontal scrolling.
 *
 * THEMES CHANGE TYPOGRAPHY, NOT BEHAVIOUR
 * ---------------------------------------
 * The three themes differ in family, leading and indentation — the choices a
 * typesetter makes. None of them touches colour or absolute size, so switching
 * theme cannot make a book less accessible.
 */

const STYLESHEET_HREF = OCF_PATHS.stylesheet.replace(`${OCF_PATHS.contentRoot}/`, '')

interface Theme {
  readonly id: string
  readonly label: string
  readonly bodyFamily: string
  readonly headingFamily: string
  readonly lineHeight: string
  /** First-line indent for continuation paragraphs. */
  readonly paragraphIndent: string
  readonly paragraphSpacing: string
}

/**
 * Font families are *stacks ending in a generic*, never a single named font.
 *
 * Fonts are not embedded (Phase 4 does not require it), so a named family is a
 * request the device may not be able to honour. Ending in `serif` or
 * `sans-serif` guarantees the reading system falls back to something sensible
 * rather than to its default at an unexpected size.
 */
const THEMES: readonly Theme[] = [
  {
    id: 'classic',
    label: 'Classic',
    bodyFamily: '"Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif',
    headingFamily: '"Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif',
    lineHeight: '1.5',
    // Indented continuation paragraphs with no space between them: the
    // convention for prose fiction, and what a novel should look like.
    paragraphIndent: '1.2em',
    paragraphSpacing: '0',
  },
  {
    id: 'modern',
    label: 'Modern',
    bodyFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    headingFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    lineHeight: '1.65',
    // Block paragraphs: the convention for non-fiction and technical writing,
    // where paragraphs are units of argument rather than of narrative.
    paragraphIndent: '0',
    paragraphSpacing: '0.9em',
  },
  {
    id: 'compact',
    label: 'Compact',
    bodyFamily: 'Georgia, "Times New Roman", serif',
    headingFamily: 'Georgia, "Times New Roman", serif',
    lineHeight: '1.35',
    paragraphIndent: '1em',
    paragraphSpacing: '0',
  },
]

export function createStylesheetGenerator(): CssGenerator {
  return {
    id: 'stylesheet',
    themes: THEMES.map((theme) => theme.id),

    generate(context: GenerationContext): Result<GeneratedFile> {
      // An unknown theme falls back to the first rather than failing: a book
      // set in a theme a later version removed should still convert.
      const theme = THEMES.find((item) => item.id === context.settings.theme) ?? THEMES[0]

      return ok({
        resource: {
          id: 'stylesheet',
          href: STYLESHEET_HREF,
          mediaType: 'text/css',
        },
        content: renderStylesheet(theme as Theme, context),
      })
    },
  }
}

function renderStylesheet(theme: Theme, context: GenerationContext): string {
  // Roles carried over from the manuscript become classes, so an author who
  // styled an epigraph in Word gets an epigraph in the book.
  const roles = collectRoles(context)

  return `@charset "utf-8";

/*
 * ${escapeComment(context.metadata.title || 'Untitled')}
 * Generated by Chiify Toolkit — theme: ${theme.label}
 *
 * Sizes are relative and colours are inherited, so the reader's own settings
 * — font size, night mode, margins — continue to work. Nothing here fixes a
 * colour on body text or a size in absolute units.
 */

html {
  /* Let the reading system size the root; everything below is relative. */
  font-size: 100%;
}

body {
  font-family: ${theme.bodyFamily};
  line-height: ${theme.lineHeight};
  /* No margin: the reading system owns the page margins, and adding our own
     produces a double gutter on devices that already inset the text. */
  margin: 0;
  padding: 0;
  /* Left-aligned rather than justified: without hyphenation — which reading
     systems apply inconsistently — justified text produces rivers of
     whitespace on a narrow screen. */
  text-align: left;
  widows: 2;
  orphans: 2;
}

/* ---------- Headings ---------- */

h1, h2, h3, h4, h5, h6 {
  font-family: ${theme.headingFamily};
  font-weight: bold;
  line-height: 1.25;
  /* Avoid a heading stranded at the foot of a page. */
  page-break-after: avoid;
  break-after: avoid;
  page-break-inside: avoid;
  break-inside: avoid;
  text-align: left;
  margin: 1.6em 0 0.8em;
}

h1 { font-size: 1.7em; margin-top: 0; }
h2 { font-size: 1.4em; }
h3 { font-size: 1.2em; }
h4 { font-size: 1.05em; }
h5, h6 { font-size: 1em; }

/* ---------- Paragraphs ---------- */

p {
  margin: 0 0 ${theme.paragraphSpacing};
  text-indent: ${theme.paragraphIndent};
  hyphens: auto;
  -webkit-hyphens: auto;
}

/* The first paragraph after a heading or a break is never indented — the
   indent exists to signal continuation, and there is nothing to continue. */
h1 + p, h2 + p, h3 + p, h4 + p, h5 + p, h6 + p,
hr + p, figure + p, blockquote + p, .page-break + p {
  text-indent: 0;
}

/* ---------- Structure ---------- */

hr.scene-break {
  border: 0;
  margin: 1.6em 0;
  text-align: center;
  /* Rendered as centred asterisks rather than a rule: a horizontal line
     across an e-reader page reads as a division of the book, not a scene. */
  overflow: visible;
}

hr.scene-break::after {
  content: "* * *";
  letter-spacing: 0.4em;
}

.page-break {
  page-break-before: always;
  break-before: page;
}

/* ---------- Quotations ---------- */

blockquote {
  margin: 1.2em 1.5em;
  font-style: italic;
}

blockquote p {
  text-indent: 0;
  margin-bottom: 0.6em;
}

blockquote .attribution {
  font-style: normal;
  font-size: 0.9em;
  text-align: right;
}

/* ---------- Lists ---------- */

ul, ol {
  margin: 0.8em 0 0.8em 1.4em;
  padding: 0;
}

li {
  margin-bottom: 0.35em;
  /* List items are never indented: the marker already signals the level. */
  text-indent: 0;
}

li p { text-indent: 0; }

/* ---------- Images ---------- */

figure.illustration {
  margin: 1.4em 0;
  text-align: center;
  page-break-inside: avoid;
  break-inside: avoid;
}

img {
  /* The pair that makes an illustration responsive: never wider than the
     column, and never distorted when it is scaled down. */
  max-width: 100%;
  height: auto;
}

figcaption {
  font-size: 0.85em;
  font-style: italic;
  margin-top: 0.5em;
  text-indent: 0;
}

/* ---------- Tables ---------- */

table {
  /* Tables are the one thing that genuinely does not reflow. Full width plus
     a smaller size is the best compromise on a phone. */
  width: 100%;
  border-collapse: collapse;
  margin: 1.2em 0;
  font-size: 0.9em;
  page-break-inside: avoid;
  break-inside: avoid;
}

caption {
  font-size: 0.9em;
  font-style: italic;
  margin-bottom: 0.4em;
  text-align: left;
}

th, td {
  /* "currentColor" rather than a fixed grey: the border follows the reader's
     text colour, so it stays visible in night mode. */
  border: 1px solid currentColor;
  padding: 0.4em 0.6em;
  text-align: left;
  text-indent: 0;
  vertical-align: top;
}

th {
  font-weight: bold;
}

/* ---------- Code ---------- */

pre {
  font-family: "SF Mono", Menlo, Consolas, monospace;
  font-size: 0.85em;
  /* Wrap rather than scroll: a reading system rarely offers horizontal
     scrolling, so an unwrapped line is simply lost off the edge. */
  white-space: pre-wrap;
  word-wrap: break-word;
  overflow-wrap: break-word;
  margin: 1.2em 0;
  padding: 0.8em;
  border: 1px solid currentColor;
  border-radius: 3px;
}

code {
  font-family: "SF Mono", Menlo, Consolas, monospace;
  font-size: 0.9em;
}

/* ---------- Notes ---------- */

aside[epub|type~="footnote"],
aside.footnote {
  font-size: 0.9em;
  margin: 0.6em 0;
}

.note-marker {
  font-weight: bold;
}

/* ---------- Navigation ---------- */

nav[epub|type~="toc"] ol {
  list-style: none;
  margin-left: 0;
  padding-left: 0;
}

nav[epub|type~="toc"] ol ol {
  margin-left: 1.2em;
}

nav[epub|type~="toc"] a {
  text-decoration: none;
}

/* ---------- Cover ---------- */

.cover-page {
  text-align: center;
  page-break-after: always;
  break-after: page;
}

.cover-page img {
  max-height: 100%;
}

.cover-title {
  font-size: 2em;
  margin-bottom: 0.3em;
}

.cover-subtitle {
  font-size: 1.2em;
  font-style: italic;
  margin-bottom: 1.5em;
}

.cover-author {
  font-size: 1.1em;
}

/* ---------- Alignment ---------- */

.align-center { text-align: center; text-indent: 0; }
.align-end { text-align: right; text-indent: 0; }
.align-justify { text-align: justify; }
${roles}
`
}

/**
 * Emit a class for every semantic role the manuscript used.
 *
 * Known roles get a considered treatment; unknown ones get a rule that does
 * nothing but exist, so the class in the XHTML always resolves. Silently
 * dropping a role would lose formatting the author deliberately applied.
 */
function collectRoles(context: GenerationContext): string {
  const roles = new Set<string>()

  for (const chapter of context.document.chapters) {
    for (const block of chapter.blocks) {
      if (block.type === 'paragraph' && block.role) roles.add(block.role)
    }
  }

  if (roles.size === 0) return ''

  const known: Record<string, string> = {
    epigraph: '  font-style: italic;\n  margin: 1.5em 2em;\n  text-indent: 0;',
    dedication: '  font-style: italic;\n  text-align: center;\n  margin: 2em 0;\n  text-indent: 0;',
    subtitle: '  font-size: 1.2em;\n  font-style: italic;\n  text-indent: 0;',
    title: '  font-size: 1.6em;\n  font-weight: bold;\n  text-align: center;\n  text-indent: 0;',
    caption: '  font-size: 0.85em;\n  font-style: italic;\n  text-indent: 0;',
  }

  const rules = [...roles].sort().map((role) => {
    const declarations = known[role] ?? '  text-indent: 0;'
    return `.role-${safeXmlId(role, 'role')} {\n${declarations}\n}`
  })

  return `\n/* ---------- Manuscript roles ---------- */\n\n${rules.join('\n\n')}\n`
}

/** Prevent a title containing a comment terminator from closing the CSS comment. */
function escapeComment(value: string): string {
  return value.replace(/\*\//g, '*\\/')
}

export { STYLESHEET_HREF, THEMES }
